<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AQMIT-LPT-10781" failures="1" tests="5" name="com.github.testCase.AddContact" time="0.019" errors="0" timestamp="02 May 2022 05:58:20 GMT" skipped="3">
  <testcase classname="com.github.testCase.AddContact" name="checkResponseBody" time="0.018"/>
  <testcase classname="com.github.testCase.AddContact" name="checkResponseCode" time="0.001">
    <failure message="Response code is not 201" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Response code is not 201
at org.testng.Assert.fail(Assert.java:96)
at com.github.utils.AssertionUtils.assertForTrue(AssertionUtils.java:34)
at com.github.testCase.AddContact.checkResponseCode(AddContact.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkResponseCode -->
  <testcase classname="com.github.testCase.AddContact" name="checkResponseTime">
    <skipped/>
  </testcase> <!-- checkResponseTime -->
  <testcase classname="com.github.testCase.AddContact" name="checkStatusLine">
    <skipped/>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="com.github.testCase.AddContact" name="checkContentType">
    <skipped/>
  </testcase> <!-- checkContentType -->
</testsuite> <!-- com.github.testCase.AddContact -->
